###
GET http://localhost:3333/products

###
POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "Camiseta Preta",
  "price": 49.90,
  "description": "Camiseta 100% algodão",
  "stock": 10
}

###
GET http://localhost:3333/products/eb9b798d-d43b-46e0-a425-a3a52f41c8d4

###
GET http://localhost:3333/products/id-falso

###
PATCH http://localhost:3333/products/eb9b798d-d43b-46e0-a425-a3a52f41c8d4
Content-Type: application/json

{
  "price": 59.90
}

###
PATCH http://localhost:3333/products/id-falso
Content-Type: application/json

{
  "price": 59.90
}

###
DELETE http://localhost:3333/products/eb9b798d-d43b-46e0-a425-a3a52f41c8d4

###
POST http://localhost:3333/register
Content-Type: application/json

{
  "email": "felipe@teste.com",
  "password": "123456"
}