###
POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "Felipe",
  "email": "felipe@teste.com",
  "password": "123456"
}

###
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "felipe@teste.com",
  "password": "123456"
}

###
GET http://localhost:3333/products

###
POST http://localhost:3333/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMTExZGZlNy1iZDJkLTRmYTItYjRjZS1mMDFiMjUwOWViNjUiLCJpYXQiOjE3NzY1Mjc5MzUsImV4cCI6MTc3NjUzMTUzNX0.iUZW71RCHiNzvIXtBAj3TEPZSm2TXjeuYTq-uhbud74

{
  "items": [
    {"productId": "prod-001", "quantity": 2 }
  ]
}

###
GET http://localhost:3333/orders/52013656-fff1-4c40-a829-2e091e094afb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMTExZGZlNy1iZDJkLTRmYTItYjRjZS1mMDFiMjUwOWViNjUiLCJpYXQiOjE3NzY1Mjc5MzUsImV4cCI6MTc3NjUzMTUzNX0.iUZW71RCHiNzvIXtBAj3TEPZSm2TXjeuYTq-uhbud74

###
POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@teste.com",
  "password": "123456"
}

###
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "maria@teste.com",
  "password": "123456"
}

###
GET http://localhost:3333/orders/52013656-fff1-4c40-a829-2e091e094afb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyODE3MjkzNy05OTk5LTQ3N2EtYmY5Yy0xNzI2MWU1ZjRhODkiLCJpYXQiOjE3NzY1Mjg2OTgsImV4cCI6MTc3NjUzMjI5OH0.tl81L4DvinlNGt3vquT-yqiM-cZM5jyzdd3EswNHFNw